
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const fallbackDatabaseUrl = "mongodb://127.0.0.1:27017/puram-consultancy-website";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Allow client generation in local/dev environments before a real DB URL is configured.
    url: process.env.DATABASE_URL ?? fallbackDatabaseUrl,
  },
});
